[package]
name = "prometheus-weathermen"
description = "A prometheus exporter for weather data from various weather APIs"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["prometheus", "prometheus-exporter", "weather", "monitoring"]
categories = ["command-line-utilities"]
repository = "https://github.com/lstrojny/prometheus-weathermen"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["tls"] }
reqwest = { version = "0.11.14", features = ["json", "blocking"] }
serde = "1.0.152"
toml = "0.7.0"
hmac = "0.12.1"
hex = "0.4.3"
sha2 = "0.10.6"
serde_json = "1.0.91"
moka = "0.9.6"
humantime-serde = "1.1.1"
anyhow = "1.0.68"
log = { version = "0.4.17", features = ["serde"] }
tokio = { version = "1.25.0", default-features = false }
clap = { version = "4.1.4", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
figment = { version = "0.10.8", features = ["toml", "env"] }
prometheus-client = "0.19.0"
rocket-basicauth = "2.1.1"
bcrypt = "0.13.0"
openssl = { version = "0.10.45", features = ["vendored"] }
simple_logger = { version = "4.0.0", features = ["timestamps", "colors", "stderr"] }
csv = "1.1.6"
const_format = "0.2.30"
geo = "0.23.1"
chrono = { version = "0.4.23", default-features = false, features = ["serde"] }
zip = { version = "0.6.3", default-features = false, features = ["deflate-miniz"] }
failsafe = "1.2.0"
once_cell = "1.17.0"

[target.'cfg(target_os = "linux")'.dependencies]
systemd-journal-logger = "0.7.0"

[dev-dependencies]
assert-str = "0.1.0"
