[package]
name = "prometheus-weathermen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
opentelemetry = "0.18.0"
opentelemetry-prometheus = "0.11.0"
prometheus = "0.13.3"
reqwest = { version = "0.11.13", features = ["json", "blocking"] }
serde = "1.0.152"
toml = "0.5.10"
itertools = "0.10.5"
hmac = "0.12.1"
hex = "0.4.3"
sha2 = "0.10.6"
serde_json = "1.0.91"
moka = "0.9.6"
humantime-serde = "1.1.1"
