[package]
name = "prometheus-weathermen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
opentelemetry = "0.18.0"
opentelemetry-prometheus = "0.11.0"
prometheus = "0.13.3"
reqwest = { version = "0.11.13", features = ["json", "blocking"] }
serde = "1.0.152"
toml = "0.5.10"
hmac = "0.12.1"
hex = "0.4.3"
sha2 = "0.10.6"
serde_json = "1.0.91"
moka = "0.9.6"
humantime-serde = "1.1.1"
anyhow = "1.0.68"
log = { version = "0.4.17", default-features = false, features = ["serde"] }
stderrlog = { version = "0.5.4", default-features = false, features = ["timestamps"] }
tokio = { version = "1.24.1", default-features = false }
clap = { version = "4.0.32", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
